import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#020617",
              color: "#e5e7eb",
              border: "1px solid #1f2937",
            },
            success: {
              iconTheme: {
                primary: "#22c55e",
                secondary: "#020617",
              },
              style: {
                background: "#022c22",
                color: "#e5e7eb",
                border: "1px solid #16a34a",
              },
            },
            error: {
              iconTheme: {
                primary: "#f97316",
                secondary: "#020617",
              },
              style: {
                background: "#450a0a",
                color: "#fee2e2",
                border: "1px solid #b91c1c",
              },
            },
            loading: {
              style: {
                background: "#020617",
                color: "#e5e7eb",
                border: "1px solid #1f2937",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
